### ISSUE TITLE
Callback Query Trigger does not work

### ISSUE THREAD

**Issue by tlux** [windkh/node-red-contrib-telegrambot#134]
Hello there, thank you for this great package.

However, I've got a problem with the Inline Keyboard/Callback Query Trigger. 

The inline keyboard does show up properly but after pressing a button it does not trigger the callback query trigger node. 
I've even tried the [inline keyboard example](https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/inlinekeyboard.json) from this very repo and it still does not trigger.

I wonder if I am missing something. Do you have any hints for me?

**Comment by windkh** [comment]
Thanks for reporting. I believe a bug found his way into the code during refactoring:. Version 8.7.1 should fix it.

**Comment by tlux** [comment]
Hello, @windkh and thank you for your quick response and fix!

I just upgraded to 8.7.1 but unfortunately that did not help. The Callback Query Trigger still does not trigger. Any more ideas?

**Comment by windkh** [comment]
I just tested it and added some debug nodes:
![image](https://user-images.githubusercontent.com/10910767/96546937-841af980-12ab-11eb-8bd6-e5fc710e4fcc.png)

**Comment by windkh** [comment]
any news?

**Comment by tlux** [comment]
Sadly, my last attempts with version 8.7.1 have been unsuccessful. I've been trying out Callback Queries with Home Assistant's Telegram Bot Plugin and also n8n and both worked. 

Do you use webhooks or polling then testing? I'm currently using the polling strategy and have not tried webhooks yet.

**Comment by windkh** [comment]
I use polling. Maybe we could make a online meeting tomorrow... probably we find the problem on your system.

**Comment by tlux** [comment]
After some playing around with the bot settings, I finally figured out that I had to revoke and regenerate my bot token. I really don't know why I would have to do that, but now it works like a charm. Thanks for your efforts and sorry for the troubles!

**Comment by windkh** [comment]
Ah ok very good. You are welcome
